POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "Exclua me",
    "description": "Apenas um teste",
    "price": 3000,
    "image": "https://static.vecteezy.com/ti/vetor-gratis/p1/49753728-teste-folha-projeto-isolado-em-branco-fundo-vetor.jpg"
}

###
GET http://localhost:3000/api/services

###
GET http://localhost:3000/api/services/6a8dd9f37188d53413480b65

###
DELETE  http://localhost:3000/api/services/6a8dd9f37188d53413480b65

###
PUT http://localhost:3000/api/services/6a8caa5444c4d5e6e337133d
Content-Type: application/json

{
    "name": "Teste atualização",
    "description": "Apenas um teste",
    "price": 3000,
    "image": "https://static.vecteezy.com/ti/vetor-gratis/p1/49753728-teste-folha-projeto-isolado-em-branco-fundo-vetor.jpg"
}

###
POST http://localhost:3000/api/parties
Content-Type: application/json

{
    "title": " Testando serviços",
    "author": "Davi",
    "description": "Testando com serviço",
    "budget": 3000,
    "image":"https://static.vecteezy.com/ti/vetor-gratis/p1/49753728-teste-folha-projeto-isolado-em-branco-fundo-vetor.jpg",
    "services":[
    {
        "name": "Teste",
        "description": "Apenas um teste",
        "price": 3000,
        "image": "https://static.vecteezy.com/ti/vetor-gratis/p1/49753728-teste-folha-projeto-isolado-em-branco-fundo-vetor.jpg"
    },
    {
        "name": "Teste 2",
        "description": "Apenas um teste",
        "price": 4000,
        "image": "https://static.vecteezy.com/ti/vetor-gratis/p1/49753728-teste-folha-projeto-isolado-em-branco-fundo-vetor.jpg"
    }
    ]
}

###
GET http://localhost:3000/api/parties

###
GET http://localhost:3000/api/parties/6a8f5a9ed019729640e63f3e

###
DELETE http://localhost:3000/api/parties/6a8f5a9ed019729640e63f3e

###
PUT http://localhost:3000/api/parties/6a8f5a16d019729640e63f3d
Content-Type: application/json

{
    "name": "Atualizando 2",
    "description": "Apenas um teste",
    "price": 12000,
    "image": "https://static.vecteezy.com/ti/vetor-gratis/p1/49753728-teste-folha-projeto-isolado-em-branco-fundo-vetor.jpg",
    "services": [
        {
            "name": "Teste de update",
            "description": "Apenas um teste",
            "price": 10000,
            "image": "https://static.vecteezy.com/ti/vetor-gratis/p1/49753728-teste-folha-projeto-isolado-em-branco-fundo-vetor.jpg"
        }
    ]
}

###
PUT http://localhost:3000/api/parties/6a8f5a16d019729640e63f3d
Content-Type: application/json

{
    "title": "Festa Teste Orçamento",
    "author": "Davi",
    "description": "Teste para checar validação de orçamento",
    "budget": 1000,
    "image": "https://static.vecteezy.com/ti/vetor-gratis/p1/49753728-teste-folha-projeto-isolado-em-branco-fundo-vetor.jpg",
    "services": [
        {
            "name": "Serviço A",
            "description": "Serviço caro",
            "price": 600,
            "image": "https://static.vecteezy.com/ti/vetor-gratis/p1/49753728-teste-folha-projeto-isolado-em-branco-fundo-vetor.jpg"
        },
        {
            "name": "Serviço B",
            "description": "Outro serviço caro",
            "price": 700,
            "image": "https://static.vecteezy.com/ti/vetor-gratis/p1/49753728-teste-folha-projeto-isolado-em-branco-fundo-vetor.jpg"
        }
    ]
}